title: MELT
description: "Multilingual Evaluation Toolkits"

# disabled because we are using a custom domain
# baseurl: https://ai.stanford.edu/~sttruong/melt

color-primary: "#B1040E"
color-light: "#E50808"
color-dark: "#820000"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
